[project]
name = "ai-app-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.9"
dependencies = [
    "langgraph>=1.0.2",
    "pydantic-ai>=1.12.0",
    "urllib3>=2.5.0",
]
